// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cluster.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (name) VALUES ($1) RETURNING id, name, status, created_at, updated_at
`

func (q *Queries) CreateCluster(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE FROM clusters WHERE id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCluster, id)
	return err
}

const getCluster = `-- name: GetCluster :one
SELECT id, name, status, created_at, updated_at FROM clusters WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id pgtype.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClusters = `-- name: ListClusters :many
SELECT id, name, status, created_at, updated_at FROM clusters ORDER BY created_at DESC
`

func (q *Queries) ListClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterStatus = `-- name: UpdateClusterStatus :one
UPDATE clusters SET status = $1, updated_at = now() WHERE id = $2 RETURNING id, name, status, created_at, updated_at
`

type UpdateClusterStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateClusterStatus(ctx context.Context, arg UpdateClusterStatusParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateClusterStatus, arg.Status, arg.ID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
