// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cluster struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Node struct {
	ID        pgtype.UUID
	ClusterID pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Pod struct {
	ID        pgtype.UUID
	ClusterID pgtype.UUID
	NodeID    pgtype.UUID
	Name      string
	Image     string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
