// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Cluster struct {
	ID        uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Node struct {
	ID        uuid.UUID
	ClusterID uuid.UUID
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	CpuMillis int32
	MemoryMb  int32
}

type Pod struct {
	ID        uuid.UUID
	ClusterID uuid.UUID
	NodeID    uuid.NullUUID
	Name      string
	Image     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
