// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (cluster_id, name, cpu_millis, memory_mb)
VALUES ($1, $2, $3, $4) RETURNING id, cluster_id, name, status, created_at, updated_at, cpu_millis, memory_mb
`

type CreateNodeParams struct {
	ClusterID uuid.UUID
	Name      string
	CpuMillis int32
	MemoryMb  int32
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ClusterID,
		arg.Name,
		arg.CpuMillis,
		arg.MemoryMb,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuMillis,
		&i.MemoryMb,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, cluster_id, name, status, created_at, updated_at, cpu_millis, memory_mb FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuMillis,
		&i.MemoryMb,
	)
	return i, err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT id, cluster_id, name, status, created_at, updated_at, cpu_millis, memory_mb FROM nodes WHERE cluster_id = $1 AND name = $2
`

type GetNodeByNameParams struct {
	ClusterID uuid.UUID
	Name      string
}

func (q *Queries) GetNodeByName(ctx context.Context, arg GetNodeByNameParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByName, arg.ClusterID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuMillis,
		&i.MemoryMb,
	)
	return i, err
}

const listNodesByCluster = `-- name: ListNodesByCluster :many
SELECT id, cluster_id, name, status, created_at, updated_at, cpu_millis, memory_mb FROM nodes WHERE cluster_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNodesByCluster(ctx context.Context, clusterID uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CpuMillis,
			&i.MemoryMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeStatus = `-- name: UpdateNodeStatus :one
UPDATE nodes SET status = $1, updated_at = now() WHERE id = $2 RETURNING id, cluster_id, name, status, created_at, updated_at, cpu_millis, memory_mb
`

type UpdateNodeStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeStatus, arg.Status, arg.ID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuMillis,
		&i.MemoryMb,
	)
	return i, err
}
