// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pod.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignPodToNode = `-- name: AssignPodToNode :one
UPDATE pods SET node_id = $1, status = 'scheduled', updated_at = now() WHERE id = $2 RETURNING id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request
`

type AssignPodToNodeParams struct {
	NodeID uuid.NullUUID
	ID     uuid.UUID
}

func (q *Queries) AssignPodToNode(ctx context.Context, arg AssignPodToNodeParams) (Pod, error) {
	row := q.db.QueryRow(ctx, assignPodToNode, arg.NodeID, arg.ID)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuRequest,
		&i.MemoryRequest,
	)
	return i, err
}

const createPod = `-- name: CreatePod :one
INSERT INTO pods (cluster_id, name, image, cpu_request, memory_request)
VALUES ($1, $2, $3, $4, $5) RETURNING id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request
`

type CreatePodParams struct {
	ClusterID     uuid.UUID
	Name          string
	Image         string
	CpuRequest    int32
	MemoryRequest int32
}

func (q *Queries) CreatePod(ctx context.Context, arg CreatePodParams) (Pod, error) {
	row := q.db.QueryRow(ctx, createPod,
		arg.ClusterID,
		arg.Name,
		arg.Image,
		arg.CpuRequest,
		arg.MemoryRequest,
	)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuRequest,
		&i.MemoryRequest,
	)
	return i, err
}

const deletePod = `-- name: DeletePod :exec
DELETE FROM pods WHERE id = $1
`

func (q *Queries) DeletePod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePod, id)
	return err
}

const getPod = `-- name: GetPod :one
SELECT id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request FROM pods WHERE id = $1
`

func (q *Queries) GetPod(ctx context.Context, id uuid.UUID) (Pod, error) {
	row := q.db.QueryRow(ctx, getPod, id)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuRequest,
		&i.MemoryRequest,
	)
	return i, err
}

const listPodsByCluster = `-- name: ListPodsByCluster :many
SELECT id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request FROM pods WHERE cluster_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPodsByCluster(ctx context.Context, clusterID uuid.UUID) ([]Pod, error) {
	rows, err := q.db.Query(ctx, listPodsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.Name,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CpuRequest,
			&i.MemoryRequest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodsByNode = `-- name: ListPodsByNode :many
SELECT id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request FROM pods WHERE node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPodsByNode(ctx context.Context, nodeID uuid.NullUUID) ([]Pod, error) {
	rows, err := q.db.Query(ctx, listPodsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.Name,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CpuRequest,
			&i.MemoryRequest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPodsByStatus = `-- name: ListPodsByStatus :many
SELECT id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request FROM pods WHERE cluster_id = $1 AND status = $2 ORDER BY created_at DESC
`

type ListPodsByStatusParams struct {
	ClusterID uuid.UUID
	Status    string
}

func (q *Queries) ListPodsByStatus(ctx context.Context, arg ListPodsByStatusParams) ([]Pod, error) {
	rows, err := q.db.Query(ctx, listPodsByStatus, arg.ClusterID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.NodeID,
			&i.Name,
			&i.Image,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CpuRequest,
			&i.MemoryRequest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePodStatus = `-- name: UpdatePodStatus :one
UPDATE pods SET status = $1, updated_at = now() WHERE id = $2 RETURNING id, cluster_id, node_id, name, image, status, created_at, updated_at, cpu_request, memory_request
`

type UpdatePodStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdatePodStatus(ctx context.Context, arg UpdatePodStatusParams) (Pod, error) {
	row := q.db.QueryRow(ctx, updatePodStatus, arg.Status, arg.ID)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.NodeID,
		&i.Name,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuRequest,
		&i.MemoryRequest,
	)
	return i, err
}
